routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//DENTIST ROUTES
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('dentist', 'DentistsController');
Route::get('changepassword', 'DentistsController@changepassword')->name('dentist.changepassword');
Route::post('changepasswordupdate', 'DentistsController@changepasswordupdate')->name('dentist.changepassword.update');

Route::resource('dentalcases', 'CasesController');
Route::get('dentalcases/payment/plans/{id}', 'CasesController@paymentplans')->name('dentalcases.payments');
Route::get('dentalcase/mark-as-read/{id}', 'CasesController@mark_as_read')->name('dentalcase.mark_as_read');


Route::resource('messages', 'MessagesController');

//ADMIN ROUTES
Route::post('dashboard/messages/store_admin', 'MessagesController@store_admin')->name('dashboard.messages.store');

Route::resource('dashboard', 'DashboardController');
Route::resource('dashboard/dentalcase/diagnostic', 'DiagnosticController');
Route::resource('dashboard/dentalcase/treatmentplan', 'TreatmentPlanController');
Route::post('dashboard/dentalcase/diagnostic/{dentist}', 'DiagnosticController@store')->name('diagnostic.store');
Route::post('dashboard/dentalcase/treatmentplan/{dentist}', 'TreatmentPlanController@store')->name('treatment.store');


Route::get('dentalcase/diagnostic/{dentist}', 'DiagnosticController@show_read')->name('diagnostic.show_read');
Route::get("dentalcase/diagnostic/pdf/{diagnostic}","DiagnosticController@downloadPDF")->name('diagnostic.pdf');
Route::get("dentalcase/dentist/diagnostic/pdf/{diagnostic}","DiagnosticController@downloadPDFByUser")->name('dentist.diagnostic.pdf');

Route::get('dentalcase/treatmentplan/{dentist}', 'TreatmentPlanController@show_read')->name('treatment.show_read');
Route::get("dentalcase/treatmentplan/pdf/{diagnostic}","TreatmentPlanController@downloadPDF")->name('treatment.pdf');
Route::get("dentalcase/dentist/treatmentplan/pdf/{diagnostic}","TreatmentPlanController@downloadPDFByUser")->name('dentist.treatment.pdf');


Route::get('dashboard/list/dentist', 'DashboardController@list_dentist')->name('dashboard.listdentist');
Route::get('dashboard/list/dentist/{id}', 'DashboardController@view_dentist')->name('dashboard.list.dentist');
Route::resource('dashboard', 'DashboardDentalCasesController')->only([
    'update'
])->names([
    'update' => 'dashboard.dentalcase.changestatus'
]);;
Route::get('dashboard/dentalcase/mark-as-read/{id}', 'DashboardDentalCasesController@mark_as_read')->name('dashboard.dentalcase.mark_as_read');

Route::get('dashboard/list/dentist/cases/{id}', 'DashboardController@list_dentalcases_by_dentist')->name('dashboard.list.dentist.cases');
Route::get('dashboard/list/dentalcases', 'DashboardController@list_dentalcases')->name('dashboard.list.dentalcases');
Route::get('dashboard/list/dentalcases/actives', 'DashboardController@list_dentalcases_actives')->name('dashboard.list.dentalcases.actives');
Route::get('dashboard/list/dentalcases/ended', 'DashboardController@list_dentalcases_ended')->name('dashboard.list.dentalcases.ended');
Route::get('dashboard/list/dentalcases/pending', 'DashboardController@list_dentalcases_pending')->name('dashboard.list.dentalcases.pending');
Route::get('dashboard/list/dentalcases/unread', 'DashboardController@list_dentalcases_unread')->name('dashboard.list.dentalcases.unread');
Route::get('dashboard/list/dentalcases/unread/messages', 'DashboardController@list_dentalcases_unread_messages')->name('dashboard.list.dentalcases.unread.messages');
Route::get('dashboard/dentalcase/{id}', 'DashboardController@show_dentalcase')->name('dashboard.dentalcase');
Route::get('dashboards/users', 'DashboardController@users_list')->name('dashboards.users');
Route::get('dashboards/users/edit/{id}', 'DashboardController@user_edit')->name('dashboards.users.edit');
Route::put('dashboards/users/edit/update/{dentist}', 'DashboardController@user_edit_update')->name('dashboards.users.edit_update');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\DB;
use Illuminate\Config;
use App\Dentist;
use App\Dentalcase;
use App\User;
use App\Dentist_speciality;
use App\Country;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('roleadmin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        error_log('ejecutando constructor DashboardController');
        $data = array();
        /*Mail::send('emails.test', $data, function($message) {
            $message->to('diego0123@gmail.com', 'Jon Doe')->subject('Welcome to the Laravel 4 Auth App!');
        });*/

        $dentists = Dentist::All();
        $dentists = count($dentists);

        $dentalCases = Dentalcase::All();
        $dentalCases = count($dentalCases);

        $dentalCasesActive = Dentalcase::where('status','active')->get();
        $dentalCasesActive = count($dentalCasesActive);

        $dentalCasesEnded = Dentalcase::where('status','ended')->get();
        $dentalCasesEnded = count($dentalCasesEnded);

        $dentalCasesPending = Dentalcase::where('status','pending')->get();
        $dentalCasesPending = count($dentalCasesPending);

        $dentalCasesRead = Dentalcase::where('status_read','unread')->get();
        $dentalCasesRead = count($dentalCasesRead);

        $dentalCaseswithUnReadMessages = Dentalcase::where('messages_unread_4_admin','>', '0')->get();
        $dentalCaseswithUnReadMessages = count($dentalCaseswithUnReadMessages);

        $users = User::All();
        $users = count($users);

        return view('dashboard.index', ['dentists' => $dentists
                                        , 'dentalCases' => $dentalCases
                                        , 'dentalCasesActive' => $dentalCasesActive
                                        , 'dentalCasesEnded' => $dentalCasesEnded
                                        , 'dentalCasesPending' => $dentalCasesPending
                                        , 'dentalCasesRead' => $dentalCasesRead
                                        , 'dentalCaseswithUnReadMessages' => $dentalCaseswithUnReadMessages
                                        , 'users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    
    public function list_dentist()
    {
        $dentists = Dentist::all();

        $dentists->each(function($dentists){
            $dentists->user;
            $dentists->country;
            $dentists->dentalcases_active;
            $dentists->dentalcases_unread;
            $dentists->dentalcases;
        });

        return view('dashboard/list_dentists', ['dentists' => $dentists

                        ]);
    }

    public function view_dentist($id){
        //dd(Auth::user()->id);
        //dd(config('constants.options.dentist_profile'));
        $specialities = Dentist_speciality::all();
        //$countries = DB::table('countries')->where('active', 1)->get();
        $countries = Country::select('id', 'name')->where('active', 1)->get();
        $temp = array();
        foreach ($countries as $country) {
            $temp[$country->id] = $country->name;
        }
        $countries = $temp;
        
        $dentist = Dentist::find($id);

        if($dentist == null){
            flash()->error(__('app.admin.list.dentist.show.status.pending'));
            $this->index();
            return;
        }

        $dentist->each(function($dentist){
            $dentist->user;
            $dentist->country;
            $dentist->dentalcases_active;
            $dentist->dentalcases;
        });
        
        //Dentist::where('user_id', Auth::user()->id)->first();
    
        $dentist_especialities = $dentist->dentist_especialities->all();

        $dentistxSpecialitiesIds = array();
        if($dentist_especialities != null){
            foreach ($dentist_especialities as $dentistxSpeciality) {
                array_push($dentistxSpecialitiesIds, $dentistxSpeciality->id);
           }
        }
        $user = $dentist->user;

        $dentalcases = $dentist->dentalcases;
        
         
        return view('dashboard.view_dentist', ['specialities' => $specialities
                                        , 'countries' => $countries
                                        , 'user' => $user
                                        , 'dentist' => $dentist
                                        , 'dentalcases' => $dentalcases
                                        , 'dentistxSpecialitiesIds' => $dentistxSpecialitiesIds
                                        , 'user_path' => '/storage/'.md5($user->id)
                                        , 'status' => 1
                                        , 'search' => "NA003"
                    ]);
    }

    public function list_dentalcases(Request $request)
    {
        // $dentalcases = Dentalcase::all();

        // $dentalcases->each(function($dentalcases){
        //     $dentalcases->dentist;
        // });
        $where = [];
        $dentalcases = $this->filterDentalCases($where, $request->input('search'));
        return view('dashboard/list_dentalcases', ['dentalcases' => $dentalcases,
                       'status' => '', 'search' => $request->input('search') ]);
    }

    public function list_dentalcases_by_dentist($id)
    {
        $dentist = Dentist::find($id);

        $dentist->each(function($dentist){
            $dentist->dentalcases;
        });
        return view('dashboard/list_dentalcases_by_dentist', ['dentalcases' => $dentist->dentalcases
                        ]);
    }

    public function list_dentalcases_actives(Request $request)
    {
        // $dentalcases = Dentalcase::where('status', 'active')->get();
        // $dentalcases->each(function($dentalcases){
        //     $dentalcases->dentist;
        // });
        $where = [['dentalcases.status', 'active']];
        $dentalcases = $this->filterDentalCases($where, $request->input('search'));
        return view('dashboard/list_dentalcases_active', ['dentalcases' => $dentalcases
                        ,'status' => 'actives', 'search' => $request->input('search')]);
    }

    public function list_dentalcases_ended(Request $request)
    {
        // $dentalcases = Dentalcase::where('status', 'ended')->get();
        // $dentalcases->each(function($dentalcases){
        //     $dentalcases->dentist;
        // });
        $where = [['dentalcases.status', 'ended']];
        $dentalcases = $this->filterDentalCases($where, $request->input('search'));
        return view('dashboard/list_dentalcases_ended', ['dentalcases' => $dentalcases
                        ,'status' => 'ended', 'search' => $request->input('search')]);
    }

    public function list_dentalcases_pending(Request $request)
    {
        //dd($request->all());
        // $dentalcases = Dentalcase::where('status', 'pending')->get();
        // $dentalcases->each(function($dentalcases){
        //     $dentalcases->dentist;
        // });
        $where = [['dentalcases.status', 'pending']];
        $dentalcases = $this->filterDentalCases($where, $request->input('search'));
        return view('dashboard/list_dentalcases_pending', ['dentalcases' => $dentalcases
                        ,'status' => 'pending', 'search' => $request->input('search')]);
    }

    public function list_dentalcases_unread(Request $request)
    {
        // $dentalcases = Dentalcase::where('status_read', 'unread')->get();
        // $dentalcases->each(function($dentalcases){
        //     $dentalcases->dentist;
        // });
        $where = [['dentalcases.status_read', 'unread']];
        $dentalcases = $this->filterDentalCases($where, $request->input('search'));
        return view('dashboard/list_dentalcases_unread', ['dentalcases' => $dentalcases
                        ,'status' => 'unread', 'search' => $request->input('search')]);
    }

    public function list_dentalcases_unread_messages(Request $request)
    {
        // $dentalcases = Dentalcase::where('messages_unread_4_admin', '>','0')->get();
        // $dentalcases->each(function($dentalcases){
        //     $dentalcases->dentist;
        // });
        $where = [['dentalcases.messages_unread_4_admin', '>', '0']];
        $dentalcases = $this->filterDentalCases($where, $request->input('search'));
        return view('dashboard/list_dentalcases_unread_messages', ['dentalcases' => $dentalcases
                        ,'status' => 'unread/messages', 'search' => $request->input('search')]);
    }

resources/views/dashboard/dentalcase.blade.php
@extends('layouts.admin_template')

@push('scripts')
<script src="{{ asset('js/bootstrap-datepicker.min.js') }}" ></script>
<script src="{{ asset('js/dashboard.js?time=').date('Ymdhis') }}" ></script>
@endpush

@section('content')

    @include('dentalcases.files_partial')



    <div class="modal fade" id="active" role="dialog">
      <div class="modal-dialog modal-dialog-centered">
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title"><b>@lang('app.admin.deltalcases.status.action.active')</b></h3>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <div class="container">
              <div class="row">
                {!! Form::open(['route' => ['dashboard.dentalcase.changestatus', $dentalCase], 'method' => 'PUT']) !!}
                @csrf
                <div class="form-group">
                  <label for="message-text" class="col-form-label">
                    @lang('app.dentalcase.payment.plan.select')
                  </label>
                  {{-- 'plan3' => __('app.dentalcase.payment.plan3') --}}
                  {!! Form::select('plan'
                                , ['plan1' => __('app.dentalcase.payment.plan1')
                                ,  'plan2' => __('app.dentalcase.payment.plan2')
                                ,  ]
                                , $dentalCase->plan
                                , ['placeholder' => __('app.dentalcase.payment.plan.select'),
                                  'class' => 'form-control'
                                , 'required'])
                  !!}
                  <label for="message-text" class="col-form-label">
                    @lang('app.admin.deltalcases.status.action.active.date_begin')
                  </label>
                  <div class="input-group date datepicker" data-provide="datepicker">
                      <input type="text" class="form-control datepicker" id="begin_date" name="begin_date"
                        placeholder="{{ __('app.admin.deltalcases.status.action.active.date_begin') }}" >
                      <div class="input-group-addon">
                          <span class="glyphicon glyphicon-th"></span>
                      </div>
                  </div>
                  <br>
                  <label for="message-text" class="col-form-label">
                    @lang('app.admin.deltalcases.status.action.active.date')
                  </label>
                  <input type="hidden" name="status" value="active">
                  <div class="input-group date datepicker" data-provide="datepicker">
                      <input type="text" class="form-control datepicker" id="ended_date" name="ended_date"
                        placeholder="{{  __('app.admin.deltalcases.status.action.active.date') }}" >
                      <div class="input-group-addon">
                          <span class="glyphicon glyphicon-th"></span>
                      </div>
                  </div>
                  <br>
                  <input type="submit" class="btn btn-primary" value="@lang('app.admin.deltalcases.status.action.active.action')">
                   
                </div>
                {!! Form::close() !!}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="pending" role="dialog">
      <div class="modal-dialog modal-dialog-centered">
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title"><b>@lang('app.admin.deltalcases.status.action.pending')</b></h3>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <div class="container">
              <div class="row">
                {!! Form::open(['route' => ['dashboard.dentalcase.changestatus', $dentalCase], 'method' => 'PUT']) !!}
                @csrf
                <div class="form-group">
                  <label for="message-text" class="col-form-label">
                    @lang('app.admin.deltalcases.status.pending.confirm')
                  </label>
                  <input type="hidden" name="status" value="pending">
                  <br>
                  <input type="submit" class="btn btn-primary" value="@lang('app.admin.deltalcases.status.action.pending')">
                   
                </div>
                {!! Form::close() !!}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="ended" role="dialog">
      <div class="modal-dialog modal-dialog-centered">
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title"><b>@lang('app.admin.deltalcases.status.action.ended')</b></h3>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <div class="container">
              <div class="row">
                {!! Form::open(['route' => ['dashboard.dentalcase.changestatus', $dentalCase], 'method' => 'PUT']) !!}
                @csrf
                <div class="form-group">
                  <label for="message-text" class="col-form-label">
                    @lang('app.admin.deltalcases.status.ended.confirm')
                  </label>
                  <input type="hidden" name="status" value="ended">
                  <br>
                  <input type="submit" class="btn btn-primary" value="@lang('app.admin.deltalcases.status.action.ended')">
                   
                </div>
                {!! Form::close() !!}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-6 bg-secondary">
              <h3 class="my-1">
                @lang('app.dentalcase.patient.show.trate') {{ $patient->name }} 
                (@lang('app.admin.deltalcases.status.'.$dentalCase->status))<br>
                ID: {{ $dentalCase->case_by_dentist }}
              </h3>
            </div>
             
             <div class="col-md-6 bg-secondary">
                <br>
                @if($dentalCase->status == 'pending' || $dentalCase->status == 'ended')
                  <a class="btn btn-primary text-white btn-sm float-sm-right" data-toggle="modal" data-target="#active" style="margin: 1px">
                    {{ __('app.dentalcase.patient.show.active_case') }}
                  </a>
                @endif
                @if($dentalCase->status == 'active')
                  <a class="btn btn-primary text-white btn-sm float-sm-right" data-toggle="modal" data-target="#ended" style="margin: 1px">
                    {{ __('app.dentalcase.patient.show.ended_case') }}
                  </a>
                @endif
                @if($dentalCase->status != 'pending')
                  <a class="btn btn-primary text-white btn-sm float-sm-right" data-toggle="modal" data-target="#pending" style="margin: 1px">
                    {{ __('app.dentalcase.patient.show.pending_case') }}
                  </a>
                @endif

                 @if($dentalCase->status == 'active' || $diagnostic_exists)
                  <a class="btn btn-primary text-white btn-sm float-sm-right" href="{{ route('treatmentplan.show', $dentalCase->id) }}" style="margin: 1px" target="_blank">
                    {{ __('app.dentalcase.patient.show.make_treatmentplan') }}
                  </a>
                @endif
                
                @if($dentalCase->status == 'active' || $diagnostic_exists)
                  <a class="btn btn-primary text-white btn-sm float-sm-right" href="{{ route('diagnostic.show', $dentalCase->id) }}" style="margin: 1px" target="_blank">
                    {{ __('app.dentalcase.patient.show.make_diagnostic') }}
                  </a>
                @endif
                
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-4 ">
             <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th scope="col">@lang('app.dentalcase.patient.name')</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>{{ $patient->name }}</td>
                </tr>
              </tbody>
            </table> 
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.age')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $patient->age }}</td>
                  </tr>
                </tbody>
              </table>
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.genere')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>@lang('app.dentalcase.patient.genere.'.$patient->genere )</td>
                  </tr>
                </tbody>
              </table>   
              @if($patient->objective_patient != "")           
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.objective_patient')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $patient->objective_patient}}</td>
                  </tr>
                </tbody>
              </table>
              @endif
              @if($patient->objective_dentist != "")           
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.objective_dentist')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $patient->objective_dentist}}</td>
                  </tr>
                </tbody>
              </table>
              @endif
              @if($dentalCase->begin_date != "")           
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.begin_date')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $dentalCase->begin_date}}</td>
                  </tr>
                </tbody>
              </table>
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.end_date')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $dentalCase->ended_date}}</td>
                  </tr>
                </tbody>
              </table>
              @endif
              @if($dentalCase->plan != "")           
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.payment.plan.title')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>@lang('app.dentalcase.payment.'.$dentalCase->plan)</td>
                  </tr>
                </tbody>
              </table>
              @endif
              <a class="btn btn-primary text-white" data-toggle="modal" data-target=".file-list-modal">
              {{ __('app.dentalcase.patient.show.files') }}</a>
            </div>
            <div class="col-md-8 ">
              
              @include('dashboard.message_partial')

            </div>
          </div>
          <br>
          
          
          <hr>
      </div>
    </div>

@endsection

resources/views/dashboard/dentalcase_treatment.blade.php
@extends('layouts.admin_template')

@push('scripts')
<script src="{{ asset('js/dashboard.js') }}" ></script>
@endpush

@section('content')

    @include('dentalcases.files_partial')

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-6 bg-secondary">
              <h3 class="my-1">
                @lang('app.dentalcase.patient.show.trate') {{ $patient->name }} 
                (@lang('app.admin.deltalcases.status.'.$dentalCase->status))<br>
                ID: {{ $dentalCase->case_by_dentist }}
              </h3>
            </div>
             <div class="col-md-2 bg-secondary">
              
            </div>
             <div class="col-md-4 bg-secondary">
                <br>
               
                  <a class="btn btn-warning btn-sm float-sm-right" style="margin: 1px" href="{{ route('dashboard.dentalcase', $dentalCase->id) }}">
                    {{ __('app.general.back_btn') }}
                  </a>
                  @if($diagnostic != "" && $dentalCase['diagnostic']['snplan'] != "N")
                  <a class="btn btn-dark btn-sm float-sm-right" style="margin: 1px" href="{{ route('treatment.pdf', $dentalCase['diagnostic']['id']) }}">
                    {{ __('app.admin.deltalcase.diagnostic.pdf.btn') }}
                  </a>
                  @endif
                
                
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-12 bg-secondary text-center">
              <h3 class="my-1">
                @lang('app.admin.deltalcase.treatment.title')
              </h3>
            </div>            
          </div>
          <br>
          <div class="row">
            <div class="col-md-12 ">
              
              @include('dashboard.dentalcase_treatment_fields')

            </div>
          </div>
          <br>
          
          
          <hr>
      </div>
    </div>
  </div>
@endsection

resources/views/dashboard/list_dentalcases.blade.php
@extends('layouts.admin_template')

@push('scripts')
<script src="{{ asset('js/dashboard.js') }}" ></script>
@endpush

@section('content')

        <br>  
        <div class="container">
          <div class="row">
            <div class="col-md-12 bg-secondary">
              <h1 class="text-center my-1">@lang('app.admin.menu.option3')</h1>
            </div>
          </div>

          @include('dashboard.dentalcases_table')
          
        </div>
      
    
    
@endsection

resources/views/dashboard/list_dentalcases_active.blade.php
@extends('layouts.admin_template')

@push('scripts')
<script src="{{ asset('js/dashboard.js') }}" ></script>
@endpush

@section('content')

        <br>  
        <div class="container">
          <div class="row">
            <div class="col-md-12 bg-secondary">
              <h1 class="text-center my-1">@lang('app.admin.menu.option4')</h1>
            </div>
          </div>

          @include('dashboard.dentalcases_table')
          
        </div>
      
    
    
@endsection

resources/views/dashboard/list_dentalcases_by_dentist.blade.php
@extends('layouts.admin_template')

@push('scripts')
<script src="{{ asset('js/dashboard.js') }}" ></script>
@endpush

@section('content')

        <br>  
        <div class="container">
          <div class="row">
            <div class="col-md-12 bg-secondary">
              <h1 class="text-center my-1">@lang('app.admin.menu.option3')</h1>
            </div>
          </div>

          @include('dashboard.dentalcases_table')
          
        </div>
      
    
    
@endsection

resources/views/dashboard/list_dentalcases_ended.blade.php
@extends('layouts.admin_template')

@push('scripts')
<script src="{{ asset('js/dashboard.js') }}" ></script>
@endpush

@section('content')

        <br>  
        <div class="container">
          <div class="row">
            <div class="col-md-12 bg-secondary">
              <h1 class="text-center my-1">@lang('app.admin.menu.option5')</h1>
            </div>
          </div>

          @include('dashboard.dentalcases_table')
          
        </div>
      
    
    
@endsection

resources/views/dashboard/list_dentalcases_pending.blade.php
@extends('layouts.admin_template')

@push('scripts')
<script src="{{ asset('js/dashboard.js') }}" ></script>
@endpush

@section('content')

        <br>  
        <div class="container">
          <div class="row">
            <div class="col-md-12 bg-secondary">
              <h1 class="text-center my-1">@lang('app.admin.menu.option8')</h1>
            </div>
          </div>

          @include('dashboard.dentalcases_table')
          
        </div>
      
    
    
@endsection