routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//DENTIST ROUTES
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('dentist', 'DentistsController');
Route::get('changepassword', 'DentistsController@changepassword')->name('dentist.changepassword');
Route::post('changepasswordupdate', 'DentistsController@changepasswordupdate')->name('dentist.changepassword.update');

Route::resource('dentalcases', 'CasesController');
Route::get('dentalcases/payment/plans/{id}', 'CasesController@paymentplans')->name('dentalcases.payments');
Route::get('dentalcase/mark-as-read/{id}', 'CasesController@mark_as_read')->name('dentalcase.mark_as_read');


Route::resource('messages', 'MessagesController');

//ADMIN ROUTES
Route::post('dashboard/messages/store_admin', 'MessagesController@store_admin')->name('dashboard.messages.store');

Route::resource('dashboard', 'DashboardController');
Route::resource('dashboard/dentalcase/diagnostic', 'DiagnosticController');
Route::resource('dashboard/dentalcase/treatmentplan', 'TreatmentPlanController');
Route::post('dashboard/dentalcase/diagnostic/{dentist}', 'DiagnosticController@store')->name('diagnostic.store');
Route::post('dashboard/dentalcase/treatmentplan/{dentist}', 'TreatmentPlanController@store')->name('treatment.store');


Route::get('dentalcase/diagnostic/{dentist}', 'DiagnosticController@show_read')->name('diagnostic.show_read');
Route::get("dentalcase/diagnostic/pdf/{diagnostic}","DiagnosticController@downloadPDF")->name('diagnostic.pdf');
Route::get("dentalcase/dentist/diagnostic/pdf/{diagnostic}","DiagnosticController@downloadPDFByUser")->name('dentist.diagnostic.pdf');

Route::get('dentalcase/treatmentplan/{dentist}', 'TreatmentPlanController@show_read')->name('treatment.show_read');
Route::get("dentalcase/treatmentplan/pdf/{diagnostic}","TreatmentPlanController@downloadPDF")->name('treatment.pdf');
Route::get("dentalcase/dentist/treatmentplan/pdf/{diagnostic}","TreatmentPlanController@downloadPDFByUser")->name('dentist.treatment.pdf');


Route::get('dashboard/list/dentist', 'DashboardController@list_dentist')->name('dashboard.listdentist');
Route::get('dashboard/list/dentist/{id}', 'DashboardController@view_dentist')->name('dashboard.list.dentist');
Route::resource('dashboard', 'DashboardDentalCasesController')->only([
    'update'
])->names([
    'update' => 'dashboard.dentalcase.changestatus'
]);;
Route::get('dashboard/dentalcase/mark-as-read/{id}', 'DashboardDentalCasesController@mark_as_read')->name('dashboard.dentalcase.mark_as_read');

Route::get('dashboard/list/dentist/cases/{id}', 'DashboardController@list_dentalcases_by_dentist')->name('dashboard.list.dentist.cases');
Route::get('dashboard/list/dentalcases', 'DashboardController@list_dentalcases')->name('dashboard.list.dentalcases');
Route::get('dashboard/list/dentalcases/actives', 'DashboardController@list_dentalcases_actives')->name('dashboard.list.dentalcases.actives');
Route::get('dashboard/list/dentalcases/ended', 'DashboardController@list_dentalcases_ended')->name('dashboard.list.dentalcases.ended');
Route::get('dashboard/list/dentalcases/pending', 'DashboardController@list_dentalcases_pending')->name('dashboard.list.dentalcases.pending');
Route::get('dashboard/list/dentalcases/unread', 'DashboardController@list_dentalcases_unread')->name('dashboard.list.dentalcases.unread');
Route::get('dashboard/list/dentalcases/unread/messages', 'DashboardController@list_dentalcases_unread_messages')->name('dashboard.list.dentalcases.unread.messages');
Route::get('dashboard/dentalcase/{id}', 'DashboardController@show_dentalcase')->name('dashboard.dentalcase');
Route::get('dashboards/users', 'DashboardController@users_list')->name('dashboards.users');
Route::get('dashboards/users/edit/{id}', 'DashboardController@user_edit')->name('dashboards.users.edit');
Route::put('dashboards/users/edit/update/{dentist}', 'DashboardController@user_edit_update')->name('dashboards.users.edit_update');

resources/views/dentalcases/dentalcase_diagnostic.blade.php
@extends('layouts.dentist_template')

@push('scripts')
<script src="{{ asset('js/dentalcases.js') }}" ></script>
@endpush

@section('content')

    @include('dentalcases.files_partial')


    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-6 bg-secondary">
              <h3 class="my-1">
                @lang('app.dentalcase.patient.show.trate') {{ $patient->name }}<br>
                ID: {{ $dentalCase->case_by_dentist }}
              </h3>
            </div>
             <div class="col-md-2 bg-secondary">
              
            </div>
             <div class="col-md-4 bg-secondary">
                <br>
               
                  <a class="btn btn-warning btn-sm float-sm-right" href="{{ route('dentalcases.show', $dentalCase->id) }}">
                    {{ __('app.general.back_btn') }}
                  </a>

                  <a class="btn btn-dark btn-sm float-sm-right" href="{{ route('dentist.diagnostic.pdf', $dentalCase['diagnostic']['id']) }}">
                    {{ __('app.admin.deltalcase.diagnostic.pdf.btn') }}
                  </a>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-3 ">
             <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th scope="col">@lang('app.dentalcase.patient.name')</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>{{ $patient->name }}</td>
                </tr>
              </tbody>
            </table> 
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.age')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $patient->age }}</td>
                  </tr>
                </tbody>
              </table>
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.genere')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>@lang('app.dentalcase.patient.genere.'.$patient->genere )</td>
                  </tr>
                </tbody>
              </table>   
              @if($patient->objective_patient != "")           
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.objective_patient')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $patient->objective_patient}}</td>
                  </tr>
                </tbody>
              </table>
              @endif
              @if($patient->objective_dentist != "")           
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.objective_dentist')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $patient->objective_dentist}}</td>
                  </tr>
                </tbody>
              </table>
              @endif
              <a class="btn btn-primary text-white" data-toggle="modal" data-target=".file-list-modal">
              {{ __('app.dentalcase.patient.show.files') }}</a>
            </div>
            <div class="col-md-9 ">
              
              <br>
              <div class="row">
                <div class="col-md-12 bg-secondary text-center">
                  <h3 class="my-1">
                    @lang('app.admin.deltalcase.diagnostic.title')
                  </h3>
                </div>            
              </div>
              <br>
              <div class="row">
                <div class="col-md-12 ">
                  
                  @include('dentalcases.dentalcase_diagnostic_fields')

                </div>
              </div>

            </div>
          </div>
          <br>
          
          
          <hr>
      </div>
    </div>

@endsection

resources/views/dentalcases/dentalcase_diagnostic_fields.blade.php
@foreach($diagnostic_json as $group)
		@php
			if($group['type'] == 'break'){
				continue;
			}
			$class = 'col';
			if($group['type'] == 'title'){
				$class = 'col-sm-12';
			}
			$cols = 0;
		@endphp

		<div class="row">
			<div class="{{ $class }}">
				<h3>
					<b>
						{{ $group['title'] }}
					</b>
				</h3>
			</div>
		</div>
		@if(isset($group['fields']) && count($group['fields']) > 0)
			<div class="row">
				@php
					$cols = 0;
				@endphp
			@foreach($group['fields'] as $field)
				@php
					if($field['type'] == 'break'){
						continue;
					}
					$class = 'col';
					if(isset($field['width'])){
						$class = 'col-sm-'. $field['width'];
						$cols += $field['width'];
					}
				@endphp
				<div class="col-sm-6">
					@if($field['type'] == 'radio')
						@app_diagnostic_radios_read(['field' => $field, 'diagnostic' => $diagnostic])
						@endapp_diagnostic_radios_read
					@endif
					@if($field['type'] == 'number')
						@php
						$value = '';
						if(isset($diagnostic[$field['name']])){
							$value = $diagnostic[$field['name']];
						}
						@endphp
						<h5><b>{{ $field['title'] }}</b></h5>
						<div class="form-group"> 
				            <label style="">{{ $value }}</label>
				        </div>
					@endif
					@if($field['type'] == 'check')
						<h5><b>{{ $field['title'] }}</b></h5>
						@php
						$value = 'NA';
						if(isset($diagnostic[$field['name']])){
							$value = $diagnostic[$field['name']];
							$value = '<ul><li>'.implode("</li><li>", $value).'</li></ul>';
						}
						@endphp
						
						@php
							echo $value;
						@endphp
					@endif

					@if(isset($field['fields']) && count($field['fields']) > 0)
						@foreach($field['fields'] as $intField)
							@if($intField['type'] == 'text')
								@php
								$value = '';
								if(isset($diagnostic[$intField['name']])){
									$value = $diagnostic[$intField['name']];
								}
								@endphp
								<br>
								<label><b>{{ $intField['title'] }}:</b>&nbsp;
									{{ $value }}
								</label>
							@endif
						@endforeach
					@endif
				</div>
				@if($cols == 12)
					@php	
						$cols = 0;
					@endphp
					</div>
					<hr>
					<div class="row">
				@endif
			@endforeach
			</div>
		@endif
		@if($cols > 0)
		<hr>
		@endif
	@endforeach

    

resources/views/dentalcases/dentalcase_treatment.blade.php
@extends('layouts.dentist_template')

@push('scripts')
<script src="{{ asset('js/dentalcases.js') }}" ></script>
@endpush

@section('content')

    @include('dentalcases.files_partial')


    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-6 bg-secondary">
              <h3 class="my-1">
                @lang('app.dentalcase.patient.show.trate') {{ $patient->name }}<br>
                ID: {{ $dentalCase->case_by_dentist }}
              </h3>
            </div>
             <div class="col-md-2 bg-secondary">
              
            </div>
             <div class="col-md-4 bg-secondary">
                <br>
               
                  <a class="btn btn-warning btn-sm float-sm-right" href="{{ route('dentalcases.show', $dentalCase->id) }}">
                    {{ __('app.general.back_btn') }}
                  </a>

                  <a class="btn btn-dark btn-sm float-sm-right" href="{{ route('dentist.treatment.pdf', $dentalCase['diagnostic']['id']) }}">
                    {{ __('app.admin.deltalcase.diagnostic.pdf.btn') }}
                  </a>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-3 ">
             <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th scope="col">@lang('app.dentalcase.patient.name')</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>{{ $patient->name }}</td>
                </tr>
              </tbody>
            </table> 
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.age')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $patient->age }}</td>
                  </tr>
                </tbody>
              </table>
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.genere')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>@lang('app.dentalcase.patient.genere.'.$patient->genere )</td>
                  </tr>
                </tbody>
              </table>   
              @if($patient->objective_patient != "")           
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.objective_patient')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $patient->objective_patient}}</td>
                  </tr>
                </tbody>
              </table>
              @endif
              @if($patient->objective_dentist != "")           
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.objective_dentist')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $patient->objective_dentist}}</td>
                  </tr>
                </tbody>
              </table>
              @endif
              <a class="btn btn-primary text-white" data-toggle="modal" data-target=".file-list-modal">
              {{ __('app.dentalcase.patient.show.files') }}</a>
            </div>
            <div class="col-md-9 ">
              
              <br>
              <div class="row">
                <div class="col-md-12 bg-secondary text-center">
                  <h3 class="my-1">
                    @lang('app.admin.deltalcase.treatment.title')
                  </h3>
                </div>            
              </div>
              <br>
              <div class="row">
                <div class="col-md-12 ">
                  
                  @include('dentalcases.dentalcase_treatment_fields')

                </div>
              </div>

            </div>
          </div>
          <br>
          
          
          <hr>
      </div>
    </div>

@endsection

resources/views/dentalcases/edit.blade.php
@extends('layouts.dentist_template')

@section('loading_text')
@lang('app.dentalcase.create.loading')
@endsection

@section('content')

    {!! Form::open(['route' => ['dentalcases.update', $dentalCase], 'method' => 'PUT', 'files' => true, 'class' => 'form-2-loading']) !!}
      @csrf
      
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-12 bg-secondary">
              <h1 class="text-center my-1">@lang('app.dentalcase.case_profile_title.edit')</h1>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-4">
              <div class="form-group"> 
                @app_label(['field' => 'name', 'namespace' => 'app.dentalcase.patient'])
                @endapp_label
                  {!! Form::text('name'
                              , $patient->name
                              , ['class' => 'form-control'
                              , 'placeholder' => __('app.dentalcase.patient.name')
                              , 'required'])
                 !!}
                </div>
              </div>
            <div class="col-md-4">
              <div class="form-group"> 
                @app_label(['field' => 'age', 'namespace' => 'app.dentalcase.patient'])
                @endapp_label
                  {!! Form::number('age'
                              , $patient->age
                              , ['class' => 'form-control'
                              , 'placeholder' => __('app.dentalcase.patient.age')
                              , 'required'])
                 !!}
                </div>
              </div>
            <div class="col-md-4">
              <div class="form-group"> 
                @app_label(['field' => 'genere', 'namespace' => 'app.dentalcase.patient'])
                @endapp_label
                  {!! Form::select('genere'
                                , ['m' => __('app.dentalcase.patient.genere.m')
                                , 'f' => __('app.dentalcase.patient.genere.f')]
                                , $patient->genere
                                , ['placeholder' => __('app.dentalcase.patient.genere.select'),
                                  'class' => 'form-control'
                                , 'required'])
                  !!}
                </div>
              </div>
            
          </div>
          <div class="row">
            <div class="col-md-12 bg-secondary">
              <h1 class="text-center my-1">@lang('app.dentalcase.patient.diagnosticimages')</h1>
            </div>
          </div>

          <br>
          <div class="row">
            <div class="col-md-6">
                @app_file_w_modal_help(['field' => 'radiography1'
                                , 'patient' => $patient
                                , 'user_path' => $user_path])
                @endapp_file_w_modal_help
            </div>
            <div class="col-md-6">
                @app_file_w_modal_help(['field' => 'radiography2'
                                , 'patient' => $patient
                                , 'user_path' => $user_path])
                @endapp_file_w_modal_help
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-6">
                @app_file_w_modal_help(['field' => 'radiography3'
                                , 'patient' => $patient
                                , 'user_path' => $user_path])
                @endapp_file_w_modal_help
            </div>
            <div class="col-md-6">
                @app_file_w_modal_help(['field' => 'radiography4'
                                , 'patient' => $patient
                                , 'user_path' => $user_path])
                @endapp_file_w_modal_help
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-6">
                @app_file_w_modal_help(['field' => 'radiography5'
                                , 'patient' => $patient
                                , 'user_path' => $user_path])
                @endapp_file_w_modal_help
            </div>
            <div class="col-md-6">
              
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-12 bg-secondary">
              <h1 class="text-center my-1">@lang('app.dentalcase.patient.diagnosticimages2')</h1>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-6">
                 @app_file_w_modal_help(['field' => 'radiography6'
                                , 'patient' => $patient
                                , 'user_path' => $user_path])
                @endapp_file_w_modal_help
            </div>
            <div class="col-md-6">
                 @app_file_w_modal_help(['field' => 'radiography7'
                                , 'patient' => $patient
                                , 'user_path' => $user_path])
                @endapp_file_w_modal_help
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-6">
                 @app_file_w_modal_help(['field' => 'radiography8'
                                , 'patient' => $patient
                                , 'user_path' => $user_path])
                @endapp_file_w_modal_help
            </div>
            <div class="col-md-6">
              
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-12 bg-secondary">
              <h1 class="text-center my-1">@lang('app.dentalcase.patient.diagnosticimages3')</h1>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-6">
              @app_file_w_modal_help(['field' => 'radiography9'
                                , 'patient' => $patient
                                , 'user_path' => $user_path])
                @endapp_file_w_modal_help
            </div>
            <div class="col-md-6">
              @app_file_w_modal_help(['field' => 'radiography10'
                                , 'patient' => $patient
                                , 'user_path' => $user_path])
                @endapp_file_w_modal_help
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-6">
              @app_file_w_modal_help(['field' => 'radiography11'
                                , 'patient' => $patient
                                , 'user_path' => $user_path])
                @endapp_file_w_modal_help
            </div>
            <div class="col-md-6">
              @app_file_w_modal_help(['field' => 'radiography12'
                                , 'patient' => $patient
                                , 'user_path' => $user_path])
                @endapp_file_w_modal_help
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-6">
              @app_file_w_modal_help(['field' => 'radiography13'
                                , 'patient' => $patient
                                , 'user_path' => $user_path])
                @endapp_file_w_modal_help
            </div>
            <div class="col-md-6">
              
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-12 bg-secondary">
              <h1 class="text-center my-1">@lang('app.dentalcase.patient.objective_title')</h1>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-12">
             <div class="form-group"> <label>@lang('app.dentalcase.patient.objective_dentist')</label> 
                {{ Form::textarea('objective_dentist'
                                  ,  $patient->objective_dentist
                                  , ['size' => '4x5'
                                  , 'class' => 'form-control'
                                  , 'placeholder' => __('app.dentalcase.patient.objective_dentist')]) }}
              </div>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-12">
             <div class="form-group"> <label>@lang('app.dentalcase.patient.objective_patient')</label> 
                {{ Form::textarea('objective_patient'
                                  ,  $patient->objective_patient
                                  , ['size' => '4x5'
                                  , 'class' => 'form-control'
                                  , 'placeholder' => __('app.dentalcase.patient.objective_patient')]) }}
              </div>
            </div>
           
          </div>
          
          <hr>
      </div>
    </div>


      <div class="container">
          <div class="row">
                <div class="col-md-12 text-center">
                  <div class="justify-content-center">
                    <br>
                    <a class="btn btn-danger text-white" href="{{ route('dentalcases.show', $dentalCase->id) }}">
                    {{ __('app.dentalcase.patient.show.come_back_to_show') }}</a>
                    {{ Form::button(__('app.dentalcase.patient.edit_btn'),['class' => 'btn btn-primary submit-btn', 'id' => 'submit-btn']) }}
                    <script type="text/javascript">
                      $('#submit-btn').on("click", function () {
                        $('#loading').modal('show');
                        $('.form-2-loading').submit();
                      });
                    </script>
                  </div>
                </div>
            </div>
          </div>
      </div>
    {!! Form::close(); !!}
@endsection

resources/views/dentalcases/show_active.blade.php
@extends('layouts.dentist_template')

@push('scripts')
<script src="{{ asset('js/dentalcases.js') }}" ></script>
@endpush

@section('content')

    @include('dentalcases.files_partial')


    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-6 bg-secondary">
              <h3 class="my-1">
                @lang('app.dentalcase.patient.show.trate') {{ $patient->name }}<br>
                ID: {{ $dentalCase->case_by_dentist }}
              </h3>
            </div>
             <div class="col-md-6 bg-secondary">
                <br>
                <a class="btn btn-danger text-white btn-sm float-sm-right" style="margin: 1px" href="{{ route('dentalcases.edit', $dentalCase->id) }}">
                {{ __('app.dentalcase.patient.show.edit_case') }}</a>
                @php
                /*<a class="btn btn-primary text-white">
                {{ __('app.dentalcase.patient.show.end_case') }}</a>*/
                @endphp
                
                @if($diagnostic != null && $diagnostic['snplan'] == "S")
                <a class="btn btn-primary text-white btn-sm float-sm-right" style="margin: 1px" href="{{ route('treatment.show_read', $dentalCase->id) }}">
                    {{ __('app.admin.deltalcases.treatment.view_btn') }}
                  </a>
                @endif
                @if($diagnostic != null && $diagnostic['sndiagnostic'] == "S")
                <a class="btn btn-primary text-white btn-sm float-sm-right" style="margin: 1px" href="{{ route('diagnostic.show_read', $dentalCase->id) }}">
                    {{ __('app.admin.deltalcases.diagnostic.view_btn') }}
                  </a>
                @endif
                <a class="btn btn-warning btn-sm float-sm-right" style="margin: 1px" href="{{ route('dentalcases.index') }}">
                    {{ __('app.general.back_btn') }}</a>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-4 ">
             <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th scope="col">@lang('app.dentalcase.patient.name')</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>{{ $patient->name }}</td>
                </tr>
              </tbody>
            </table> 
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.age')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $patient->age }}</td>
                  </tr>
                </tbody>
              </table>
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.genere')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>@lang('app.dentalcase.patient.genere.'.$patient->genere )</td>
                  </tr>
                </tbody>
              </table>   
              @if($patient->objective_patient != "")           
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.objective_patient')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $patient->objective_patient}}</td>
                  </tr>
                </tbody>
              </table>
              @endif
              @if($patient->objective_dentist != "")           
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.objective_dentist')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $patient->objective_dentist}}</td>
                  </tr>
                </tbody>
              </table>
              @endif
              @if($dentalCase->begin_date != "")           
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.begin_date')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $dentalCase->begin_date}}</td>
                  </tr>
                </tbody>
              </table>
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.patient.end_date')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{ $dentalCase->ended_date}}</td>
                  </tr>
                </tbody>
              </table>
              @endif
              @if($dentalCase->plan != "")           
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col">@lang('app.dentalcase.payment.plan.title')</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>@lang('app.dentalcase.payment.'.$dentalCase->plan)</td>
                  </tr>
                </tbody>
              </table>
              @endif
              <a class="btn btn-primary text-white" data-toggle="modal" data-target=".file-list-modal">
              {{ __('app.dentalcase.patient.show.files') }}</a>
            </div>
            <div class="col-md-8 ">
              
              @include('dentalcases.message_partial')

            </div>
          </div>
          <br>
          
          
          <hr>
      </div>
    </div>

@endsection