routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//DENTIST ROUTES
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('dentist', 'DentistsController');
Route::get('changepassword', 'DentistsController@changepassword')->name('dentist.changepassword');
Route::post('changepasswordupdate', 'DentistsController@changepasswordupdate')->name('dentist.changepassword.update');

Route::resource('dentalcases', 'CasesController');
Route::get('dentalcases/payment/plans/{id}', 'CasesController@paymentplans')->name('dentalcases.payments');
Route::get('dentalcase/mark-as-read/{id}', 'CasesController@mark_as_read')->name('dentalcase.mark_as_read');


Route::resource('messages', 'MessagesController');

//ADMIN ROUTES
Route::post('dashboard/messages/store_admin', 'MessagesController@store_admin')->name('dashboard.messages.store');

Route::resource('dashboard', 'DashboardController');
Route::resource('dashboard/dentalcase/diagnostic', 'DiagnosticController');
Route::resource('dashboard/dentalcase/treatmentplan', 'TreatmentPlanController');
Route::post('dashboard/dentalcase/diagnostic/{dentist}', 'DiagnosticController@store')->name('diagnostic.store');
Route::post('dashboard/dentalcase/treatmentplan/{dentist}', 'TreatmentPlanController@store')->name('treatment.store');


Route::get('dentalcase/diagnostic/{dentist}', 'DiagnosticController@show_read')->name('diagnostic.show_read');
Route::get("dentalcase/diagnostic/pdf/{diagnostic}","DiagnosticController@downloadPDF")->name('diagnostic.pdf');
Route::get("dentalcase/dentist/diagnostic/pdf/{diagnostic}","DiagnosticController@downloadPDFByUser")->name('dentist.diagnostic.pdf');

Route::get('dentalcase/treatmentplan/{dentist}', 'TreatmentPlanController@show_read')->name('treatment.show_read');
Route::get("dentalcase/treatmentplan/pdf/{diagnostic}","TreatmentPlanController@downloadPDF")->name('treatment.pdf');
Route::get("dentalcase/dentist/treatmentplan/pdf/{diagnostic}","TreatmentPlanController@downloadPDFByUser")->name('dentist.treatment.pdf');


Route::get('dashboard/list/dentist', 'DashboardController@list_dentist')->name('dashboard.listdentist');
Route::get('dashboard/list/dentist/{id}', 'DashboardController@view_dentist')->name('dashboard.list.dentist');
Route::resource('dashboard', 'DashboardDentalCasesController')->only([
    'update'
])->names([
    'update' => 'dashboard.dentalcase.changestatus'
]);;
Route::get('dashboard/dentalcase/mark-as-read/{id}', 'DashboardDentalCasesController@mark_as_read')->name('dashboard.dentalcase.mark_as_read');

Route::get('dashboard/list/dentist/cases/{id}', 'DashboardController@list_dentalcases_by_dentist')->name('dashboard.list.dentist.cases');
Route::get('dashboard/list/dentalcases', 'DashboardController@list_dentalcases')->name('dashboard.list.dentalcases');
Route::get('dashboard/list/dentalcases/actives', 'DashboardController@list_dentalcases_actives')->name('dashboard.list.dentalcases.actives');
Route::get('dashboard/list/dentalcases/ended', 'DashboardController@list_dentalcases_ended')->name('dashboard.list.dentalcases.ended');
Route::get('dashboard/list/dentalcases/pending', 'DashboardController@list_dentalcases_pending')->name('dashboard.list.dentalcases.pending');
Route::get('dashboard/list/dentalcases/unread', 'DashboardController@list_dentalcases_unread')->name('dashboard.list.dentalcases.unread');
Route::get('dashboard/list/dentalcases/unread/messages', 'DashboardController@list_dentalcases_unread_messages')->name('dashboard.list.dentalcases.unread.messages');
Route::get('dashboard/dentalcase/{id}', 'DashboardController@show_dentalcase')->name('dashboard.dentalcase');
Route::get('dashboards/users', 'DashboardController@users_list')->name('dashboards.users');
Route::get('dashboards/users/edit/{id}', 'DashboardController@user_edit')->name('dashboards.users.edit');
Route::put('dashboards/users/edit/update/{dentist}', 'DashboardController@user_edit_update')->name('dashboards.users.edit_update');

resources/views/layouts/admin_template.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="shortcut icon" href="{{ asset(config('constants.options.favico')) }}" type="image/x-icon" />
    <title>{{ config('app.name', 'COUNSEL ORTHODONTIST') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" ></script>
    <script src="{{ asset('js/popper.min.js') }}" ></script>
    <script src="{{ asset('js/general.js') }}" ></script>

    @stack('scripts')
    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/card.css') }}" rel="stylesheet">
    <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/bootstrap-datepicker.min.css') }}" rel="stylesheet">

    
</head>
<body>
    @app_errors_modal
    @endapp_errors_modal
    @include('layouts.header.admin')
    @if(isset(session()->all()['flash_notification']))
        <div class="container py-2">
            <div class="row">
                <div class="col-md-12">
                    @include('flash::message')
                </div>
            </div>
        </div>
        <script>
        $('div.alert').not('.alert-important').delay(3000).fadeOut(100  0);
        </script>
    @endif

    <div id="app"  style="min-height: 70%">
        
            <div class="container py-2">
              <div class="row">
                <div class="col-md-2">
                  <ul class="nav nav-pills flex-column">
                    <li class="nav-item">
                      <a href="{{ route('dashboard.index') }}" class="active nav-link">
                        <i class="fa fa-home fa-home"></i>&nbsp;
                      @lang('app.admin.menu.option1')
                      </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ route('dashboard.listdentist') }}">@lang('app.admin.menu.option2')</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ route('dashboard.list.dentalcases') }}">@lang('app.admin.menu.option3')</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ route('dashboard.list.dentalcases.actives') }}">@lang('app.admin.menu.option4')</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ route('dashboard.list.dentalcases.ended') }}">@lang('app.admin.menu.option5')</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ route('dashboard.list.dentalcases.pending') }}">@lang('app.admin.menu.option8')</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ route('dashboard.list.dentalcases.unread') }}">@lang('app.admin.menu.option6')</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ route('dashboard.list.dentalcases.unread.messages') }}">@lang('app.admin.menu.option9')</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ route('dashboards.users') }}">@lang('app.admin.menu.option7')</a>
                    </li>
                  </ul>
                </div>
                <div class="col-md-10">
                    <div class="row">
                    @yield('content')   
                    </div>     
                </div>
              </div>
            </div>
            
        
    </div>
    @include('layouts.footer.footer')
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="shortcut icon" href="{{ asset(config('constants.options.favico')) }}" type="image/x-icon" />
    <title>{{ config('app.name', 'COUNSEL ORTHODONTIST') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/popper.min.js') }}" ></script>

    
    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>

    @include('layouts.header.nologin')
    @app_errors_modal
    @endapp_errors_modal
    <div id="app"  style="min-height: 70%">
        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @include('layouts.footer.footer')
</body>
</html>

resources/views/layouts/dentist_hold_template.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="shortcut icon" href="{{ asset(config('constants.options.favico')) }}" type="image/x-icon" />
    <title>{{ config('app.name', 'COUNSEL ORTHODONTIST') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" ></script>
    <script src="{{ asset('js/popper.min.js') }}" ></script>
    <script src="{{ asset('js/general.js') }}" ></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    @app_errors_modal
    @endapp_errors_modal
	@include('layouts.header.dentist_hold')
    <br>
    @include('flash::message')
    <div id="app" style="min-height: 70%">
        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @include('layouts.footer.footer')
</body>
</html>

resources/views/layouts/dentist_template.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="shortcut icon" type="image/png" href="{{ asset(config('constants.options.favico')) }}"/>
    <title>{{ config('app.name', 'COUNSEL ORTHODONTIST') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" ></script>
    <script src="{{ asset('js/popper.min.js') }}" ></script>
    <script src="{{ asset('js/general.js') }}" ></script>

    @stack('scripts')
    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet">


    <style>
    #loading {
        background: #ffffff;
        color: #666666;
        position: fixed;
        height: 100%;
        width: 100%;
        z-index: 100000;
        top: 0;
        left: 0;
        float: left;
        text-align: center;
        padding-top: 25%;
        display: none;
    }
    .loading_img{
        height: 35%;
    }
</style>
    
</head>
<body>

    <div id="loading">
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    @yield('loading_text')
                </div>
            </div>
        </div>
        <img class="loading_img" src="{{ asset(config('constants.options.loading')) }}" alt="Loading" /><br/>
    </div>
    @app_errors_modal
    @endapp_errors_modal
	@include('layouts.header.dentist')
    @if(isset(session()->all()['flash_notification']))
        <div class="container py-2">
            <div class="row">
                <div class="col-md-12">
                    @include('flash::message')
                </div>
            </div>
        </div>
        <script>
        $('div.alert').not('.alert-important').delay(3000).fadeOut(100 , 0);
        </script>
    @endif
    <div id="app" style="min-height: 70%">
        <main class="py-2">
            @yield('content')
        </main>
    </div>
    @include('layouts.footer.footer')
</body>
</html>